version: "3"
services:
  tsdb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: "tsdb"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: toughradius
      POSTGRES_USER: toughradius
      POSTGRES_PASSWORD: toughradius
      TZ: Asia/Jakarta
      LANG: en_US.UTF-8
    volumes:
      - tsdb-volume:/home/postgres/pgdata/data
    networks:
      - coolify

  loki:
    image: grafana/loki:2.7.1
    container_name: "loki"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: always
    # user: "1000"
    environment:
      - TZ=Asia/Jakarta
      - LANG=en_US.UTF-8
    command: -config.file=/etc/loki/config.yml
    volumes:
      - /etc/loki/config.yml:/etc/loki/config.yml
      - loki-volume:/loki
    ports:
      - "3100"
    networks:
      - coolify

  toughradius:
    depends_on:
      - 'tsdb'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "toughradius"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: always
    ports:
      - "1816"
      - "51817:1817"
      - "51818:1818"
      - "51819:1819"
      - "51812:1812"
      - "51812:1812/udp"
      - "51813:1813/udp"
      - "51914:1914/udp"
    volumes:
      - toughradius-volume:/var/toughradius
    environment:
      - GODEBUG=x509ignoreCN=0
      - TOUGHRADIUS_SYSTEM_DEBUG=off
      - TOUGHRADIUS_DB_HOST=tsdb
      - TOUGHRADIUS_DB_NAME=toughradius
      - TOUGHRADIUS_DB_USER=toughradius
      - TOUGHRADIUS_DB_PWD=toughradius
      - TOUGHRADIUS_RADIUS_DEBUG=off
      - TOUGHRADIUS_RADIUS_ENABLED=on
      - TOUGHRADIUS_TR069_WEB_TLS=off
      - TOUGHRADIUS_LOKI_JOB=toughradius
      - TOUGHRADIUS_LOKI_SERVER=http://loki:3100
      - TOUGHRADIUS_LOKI_ENABLE=true
      - TOUGHRADIUS_LOGGER_MODE=development
      - TOUGHRADIUS_LOGGER_FILE_ENABLE=true
      - TZ=Asia/Jakarta
      - LANG=en_US.UTF-8
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  tsdb-volume:
  loki-volume:
  toughradius-volume:
