version: "3"
services:
  loki:
    image: grafana/loki:2.7.1
    container_name: "loki"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: always
    environment:
    - TZ=Asia/Shanghai
    - LANG=zh_CN.UTF-8
    command: -config.file=/etc/loki/config.yml
    volumes:
      - /etc/loki/config.yml:/etc/loki/config.yml
      - loki-volume:/loki
    ports:
      - "3100:3100"
    networks:
      loki_network:

networks:
  loki_network:

volumes:
  loki-volume: