import { useState } from 'react';
import {
  Alert, Box, Button, Card, CardContent, Chip, Divider, Link, Stack, Typography,
} from '@mui/material';
import Grid from '@mui/material/GridLegacy';
import HelpOutlineIcon from '@mui/icons-material/HelpOutline';
import PlayCircleOutlineIcon from '@mui/icons-material/PlayCircleOutline';
import { Link as RouterLink } from 'react-router-dom';
import { useGetIdentity } from 'react-admin';
import { QuickTourDialog } from '../components/onboarding/QuickTourDialog';
import { useBranding } from '../branding/BrandingContext';

const chapters = [
  { id: 'start', title: 'Start here', text: 'Use this order for a new installation: secure the operator account, review company and billing defaults, configure a RADIUS profile and NAS, create an internet package, add a customer and subscription, then verify access with an authorized test NAS.', links: [['Account settings', '/account/settings'], ['System configuration', '/system/config']] },
  { id: 'radius', title: 'RADIUS profiles and NAS', text: 'A profile defines the access policy used by RADIUS users. A NAS is the network device that sends authentication and accounting requests. Configure the matching address, shared secret, and ports on both MWX-ISP and the device. A saved NAS record is not evidence of a successful live request.', links: [['RADIUS profiles', '/radius/profiles'], ['NAS devices', '/network/nas'], ['Online sessions', '/radius/online'], ['Accounting', '/radius/accounting']] },
  { id: 'services', title: 'Customers and service lifecycle', text: 'Create a package and associate it with the intended RADIUS profile. Create a customer, then a subscription that connects that customer and package to a RADIUS user. Review service status and billing day before activation. Use a test customer for a pilot; do not reuse an operator login as a service account.', links: [['Packages', '/isp/packages'], ['Customers', '/isp/customers'], ['Subscriptions', '/isp/subscriptions'], ['RADIUS users', '/radius/users']] },
  { id: 'billing', title: 'Billing operations', text: 'Review invoices, due dates, paid amounts, and balances. Record a payment only after it has been received. Billing automation uses the configured schedule and grace rules; automatic suspension can interrupt service, so review those defaults before enabling it. Number sequences are generated by the application.', links: [['Invoices', '/isp/invoices'], ['Payments', '/isp/payments'], ['System configuration', '/system/config']] },
  { id: 'sample-data', title: 'Sample data included on first launch', text: 'An installation with no operational or business records automatically receives clearly marked sample Nodes, NAS devices, Profiles, RADIUS Users, Customers, Packages, Subscriptions, Invoices, Payments, and disabled monitor targets during startup; no second setup command is needed. Installations that already contain configuration or business data are left unchanged, and the seed runs only once. It uses the regular customer, subscription, invoice, and payment number generation. The optional cmd/demo-seed utility can refresh or clean marked samples in a test database. Sample NAS devices and RADIUS accounts start disabled (the test password is 123456); never expose them to a real NAS or customer database. Online sessions, probe history, operators, certificates, and WhatsApp deliveries are intentionally not faked.', links: [['Nodes', '/network/nodes'], ['NAS devices', '/network/nas'], ['RADIUS profiles', '/radius/profiles'], ['Customers', '/isp/customers'], ['Packages', '/isp/packages'], ['Subscriptions', '/isp/subscriptions'], ['Invoices', '/isp/invoices'], ['Payments', '/isp/payments'], ['Network & Alerts', '/operations']] },
  { id: 'daily', title: 'Daily operations', text: 'Use Online Sessions to inspect current connections and Accounting to review reported usage. Network & Alerts contains authorized-target monitoring and incident views. A disconnect request and the resulting router behavior should be verified with the device and its logs.', links: [['Dashboard', '/'], ['Online sessions', '/radius/online'], ['Accounting', '/radius/accounting'], ['Network & Alerts', '/operations']] },
  { id: 'optional', title: 'Optional integrations', text: 'Network monitoring and WhatsApp are optional. Add only network targets you are authorized to monitor, and protect SNMP credentials. Keep WhatsApp disabled until its risk acknowledgement, operator allowlist, and test-number pairing have been reviewed. Synthetic monitoring or simulated data is not production NAS validation.', links: [['Network & Alerts', '/operations'], ['System configuration', '/system/config']] },
  { id: 'production', title: 'Production readiness and troubleshooting', text: 'Before a customer pilot, verify authentication and accounting from an authorized NAS, inspect the resulting session and accounting records, confirm device-side policy, review backup and restore procedures, and check the server logs. If status cannot be loaded, resolve the API or permission error; an unavailable check must not be treated as an empty configuration.', links: [['NAS devices', '/network/nas'], ['Online sessions', '/radius/online'], ['Accounting', '/radius/accounting'], ['System configuration', '/system/config']] },
];

const UserGuidePage = () => {
  const { branding } = useBranding();
  const { data: identity } = useGetIdentity();
  const [tourOpen, setTourOpen] = useState(false);
  const operatorId = identity?.id ?? 'operator';

  return (
    <Box sx={{ p: { xs: 1, sm: 2, md: 3 }, maxWidth: 1180, mx: 'auto' }}>
      <Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" alignItems={{ sm: 'center' }} spacing={2} sx={{ mb: 2 }}>
        <Stack direction="row" spacing={1.5} alignItems="center">
          <HelpOutlineIcon color="primary" fontSize="large" />
          <Box><Typography variant="h4" fontWeight={800}>{branding.product_name} User Guide</Typography><Typography color="text.secondary">Setup, daily operations, and service verification</Typography></Box>
        </Stack>
        <Button startIcon={<PlayCircleOutlineIcon />} variant="contained" onClick={() => setTourOpen(true)}>Take quick tour</Button>
      </Stack>
      <Alert severity="info" sx={{ mb: 2 }}>New empty installations receive sample data automatically; the optional sample-data CLI is for explicit maintenance. This guide does not verify a live NAS. Setup progress is stored only in this browser for this operator.</Alert>
      <Grid container spacing={1.5}>
        <Grid item xs={12} md={3}>
          <Card sx={{ position: { md: 'sticky' }, top: 16 }}><CardContent>
            <Typography variant="overline" color="text.secondary">IN THIS GUIDE</Typography>
            <Stack spacing={0.5} sx={{ mt: 1 }}>{chapters.map(({ id, title }) => <Link key={id} href={`#${id}`} underline="hover" color="text.primary" sx={{ py: 0.5 }}>{title}</Link>)}</Stack>
          </CardContent></Card>
        </Grid>
        <Grid item xs={12} md={9}>
          <Stack spacing={1.5}>
            {chapters.map((chapter, index) => <Card key={chapter.id} id={chapter.id} sx={{ scrollMarginTop: 16 }}><CardContent>
              <Stack direction="row" spacing={1} alignItems="center" sx={{ mb: 1 }}><Chip size="small" label={String(index + 1).padStart(2, '0')} color="primary" /><Typography variant="h6" fontWeight={750}>{chapter.title}</Typography></Stack>
              <Typography color="text.secondary" paragraph sx={{ mb: 1.5 }}>{chapter.text}</Typography>
              <Divider sx={{ mb: 1.25 }} />
              <Stack direction="row" flexWrap="wrap" gap={1}>{chapter.links.map(([label, path]) => <Button key={`${chapter.id}-${path}`} size="small" component={RouterLink} to={path}>{label}</Button>)}</Stack>
            </CardContent></Card>)}
            <Alert severity="warning">Admin settings and write actions require the appropriate role. If a link is unavailable, ask an administrator; do not share passwords, RADIUS secrets, SNMP communities, or WhatsApp pairing codes.</Alert>
          </Stack>
        </Grid>
      </Grid>
      <QuickTourDialog operatorId={operatorId} open={tourOpen} onClose={() => setTourOpen(false)} />
    </Box>
  );
};

export default UserGuidePage;
